### ISSUE TITLE
XML: Minify does strip whitespace within element

### ISSUE THREAD

**Issue by cschuff** [vkiryukhin/pretty-data#13]
pretty-data currently does not seem to strip whitespace within XML Elements.

Example:
```
<Something xmlns="a.b.c"
        xmlns:a="a.b.c.d"
        xmlns:b="a.b.c.d.e.f.g">
</Something>
```

ends up as:
```
<Something xmlns="a.b.c"
        xmlns:a="a.b.c.d"
        xmlns:b="a.b.c.d.e.f.g"></Something>
```

instead of 
```
<Something xmlns="a.b.c" xmlns:a="a.b.c.d" xmlns:b="a.b.c.d.e.f.g"></Something>
```

I can't see any valid restriction on this. Should be savely possible.

BR
Chris

**Comment by vkiryukhin** [comment]
xmlns attribute is shown on a separate line for better readability. All other attributes are shown as you expect. If you don't like it, simply comment xmlns related lines in the code.

**Comment by cschuff** [comment]
This does not only apply to xmlns attributes but to all others as well. e.g:
```
<image id="someID"
             maxWidth="100%"
             maxHeight="100%" />
```
instead of 
```
<image id="someID" maxWidth="100%" maxHeight="100%" />
```

I also don't share your opinion about better readability. When I'm minifying my code I definately do not aim for readability. So please revisit the issue.

BR
Chris
