### ISSUE TITLE
When minifying json with strings containing brackets, spaces are trimmed

### ISSUE THREAD

**Issue by joanjane** [vkiryukhin/pretty-data#21]
Hi there!
I've played around with gulp-pretty-data which wraps this library and I found an issue when minifying json files when a string contains brackets like this:

```json
{
  "welcome": "text before {{variable}} text after"
}
```

Is converted to:
```json
{"welcome":"text before{{variable}}text after"}
```

Instead of (note spaces between `{{variable}}`):
```json
{"welcome":"text before {{variable}} text after"}
```

Is there a way to fix this? I've created an [issue](https://github.com/neilcarpenter/gulp-pretty-data/issues/7) on gulp plugin, but I agree with author that the issue should be created here.

Thank you!

**Comment by vkiryukhin** [comment]
Hi joanjane,
Thank you for letting me know.  I'll take a look if I can quick fix it.

**Comment by vkiryukhin** [comment]
I've fixed it
